version: "3"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: "unless-stopped"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  server1:
    build:
      context: ./server
    container_name: server1
    expose:
      - "3000"
    volumes:
      - ./src/server1:/src
      - /src/node_modules
    restart: "unless-stopped"
  server2:
    build:
      context: ./server
    container_name: server2
    expose:
      - "3000"
    restart: "unless-stopped"
