version: "3.7"

services:
  swagger:
    labels:
      caddy: localhost crew.api.prod.sopt.org
  spring-green:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    labels:
      caddy: localhost crew.api.prod.sopt.org

  nestjs-green:
    environment:
      - NODE_ENV=prod
    labels:
      caddy: localhost crew.api.prod.sopt.org

  spring-blue:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    labels:
      caddy: localhost crew.api.prod.sopt.org

  nestjs-blue:
    environment:
      - NODE_ENV=prod
    labels:
      caddy: localhost crew.api.prod.sopt.org